# -*- coding: utf-8 -*-
# Descent via a 2-isogeny: everywhere-local-solubility of the quartics
#     C_d :  N^2 = d M^4 + A M^2 e^2 + (B/d) e^4     for E : y^2 = x(x^2+Ax+B).
# The image of  E(Q) -> Q*/Q*^2 ,  P |-> x(P)  (with T=(0,0) |-> B)  is contained in
#     S = { d squarefree, d | B : C_d is ELS },
# with equality iff Sha(E')[hatphi] = 0, where E' = E/<T>.

import sys

def is_square_Qp(a, p):
    """a in QQ (0 allowed).  True iff a is a square in Q_p."""
    a = QQ(a)
    if a == 0:
        return True
    v = a.valuation(p)
    if v % 2 != 0:
        return False
    u = a / QQ(p)**v
    t = ZZ(u.numerator() * u.denominator())     # same square class as u, prime to p
    if p == 2:
        return (t % 8) == 1
    return kronecker(t, p) == 1

def _chart_soluble(f, p, M0, k, Kmax, e2):
    """f: univariate ZZ-polynomial.  Is f(M) a square in Q_p for some M = M0 + p^k Z_p ?
       True / False / None (undecided within Kmax)."""
    v = f(M0)
    if v != 0:
        nv = ZZ(v).valuation(p)
        if nv + 2*e2 + 1 <= k:
            return is_square_Qp(v, p)
    if k >= Kmax:
        return None
    undecided = False
    pk = p**k
    for a in range(p):
        res = _chart_soluble(f, p, M0 + a*pk, k+1, Kmax, e2)
        if res is True:
            return True
        if res is None:
            undecided = True
    return None if undecided else False

def _roots_in_Qp(d, A, Bd, p, prec=200):
    """rational roots of d w^2 + A w + Bd in Q_p, or None if disc is not a square in Q_p."""
    disc = A**2 - 4*d*Bd
    K = Qp(p, prec)
    if disc == 0:
        return [K(-A)/K(2*d)]
    if not K(disc).is_square():
        return None
    sq = K(disc).sqrt()
    return [(-K(A) + sq)/(2*K(d)), (-K(A) - sq)/(2*K(d))]

def qp_soluble(d, A, Bd, p, Kmax=30):
    """Is C_d : N^2 = d M^4 + A M^2 e^2 + Bd e^4 soluble over Q_p?"""
    d = ZZ(d); A = ZZ(A); Bd = ZZ(Bd)
    # (1) if a root w of d w^2+Aw+Bd is a square in Q_p, then f has a simple zero on
    #     P^1(Q_p); near it the square class of (M^2 - w e^2) takes EVERY value while the
    #     complementary factor stays in a fixed nonzero class  ==>  soluble.
    rts = _roots_in_Qp(d, A, Bd, p)
    if rts is not None:
        for w in rts:
            if w != 0 and w.is_square():
                return True
            if w == 0:
                return True
    if is_square_Qp(d, p):        # (M:e) = (1:0)
        return True
    if is_square_Qp(Bd, p):       # (M:e) = (0:1)
        return True
    R = PolynomialRing(ZZ, 'M'); M = R.gen()
    e2 = 1 if p == 2 else 0
    und = False
    f1 = d*M**4 + A*M**2 + Bd                  # chart e = 1
    for a in range(p):
        res = _chart_soluble(f1, p, a, 1, Kmax, e2)
        if res is True:
            return True
        if res is None:
            und = True
    f2 = d + A*M**2 + Bd*M**4                  # chart M = 1, e in pZ_p
    res = _chart_soluble(f2, p, 0, 1, Kmax, e2)
    if res is True:
        return True
    if res is None:
        und = True
    if und:
        raise RuntimeError("undecided: p=%s d=%s A=%s Bd=%s" % (p, d, A, Bd))
    return False

def real_soluble(d, A, Bd):
    """f = d M^4 + A M^2 e^2 + Bd e^4 takes a value >= 0 ?"""
    if d > 0 or Bd > 0:
        return True
    disc = A**2 - 4*d*Bd
    if disc < 0:
        return False          # constant sign = sign(d) < 0
    r1 = (-A + RR(disc).sqrt())/(2*d); r2 = (-A - RR(disc).sqrt())/(2*d)
    return max(r1, r2) > 0    # need M^2 between the roots, and >= 0

def selmer_set(A, B, name="", verbose=True, Kmax=30):
    """E: y^2 = x(x^2+Ax+B), A,B in ZZ.  Return sorted list of squarefree signed d | B
       such that C_d is everywhere locally soluble."""
    A = ZZ(A); B = ZZ(B)
    disc = A**2 - 4*B
    bad = sorted(set([q for q, _ in factor(2*B*disc)]))
    primesB = [q for q, _ in factor(B)]
    out = []
    for sgn in [1, -1]:
        for sub in Subsets(primesB):
            d = ZZ(sgn) * prod(sub, ZZ(1))
            if B % d != 0:
                continue
            Bd = B // d
            if not real_soluble(d, A, Bd):
                continue
            ok = True
            for p in bad:
                if not qp_soluble(d, A, Bd, p, Kmax=Kmax):
                    ok = False
                    break
            if ok:
                out.append(d)
    out = sorted(set(out))
    if verbose:
        print("  %s : |S| = %d  (2^%s)" % (name, len(out), ZZ(len(out)).exact_log(2)))
    return out

def sqfree(x):
    x = QQ(x)
    return ZZ(x.numerator()*x.denominator()).squarefree_part()

def classgrp(gens):
    """subgroup of Q*/Q*^2 generated by gens"""
    S = set([ZZ(1)])
    for g in gens:
        g = sqfree(g)
        S |= set([sqfree(a*g) for a in S])
    return S

def model_A_B(E, T):
    """E elliptic over Q, T a rational point of order 2.  Return integers (A,B) with
       E isomorphic to y^2 = x(x^2+Ax+B) sending T to (0,0) (x scaled by a square)."""
    Ew, iso = E.short_weierstrass_model(), None
    phi = E.isomorphism_to(E.short_weierstrass_model())
    Tw = phi(T)
    rt = Tw[0]
    a1, a2, a3, a4, a6 = E.short_weierstrass_model().ainvs()
    A = 3*rt
    B = 3*rt**2 + a4
    D = lcm(QQ(A).denominator(), QQ(B).denominator())
    u = D
    return ZZ(A*u**2), ZZ(B*u**4)
